Repository edaa-org/pyEDAA.IPXACT, pull requests merged in 2021-12, with the labels that each got.

#7 v0.2.1
  .github/pull_request_template.md
  .gitignore
  Test.py
  doc/Installation.rst
  doc/Makefile
  doc/conf.py
  doc/index.rst
  doc/make.bat
  doc/pyEDAA.IPXACT/Catalog.rst
  doc/pyEDAA.IPXACT/Component.rst
  doc/pyEDAA.IPXACT/Design.rst
  doc/pyEDAA.IPXACT/DesignConfiguration.rst
  doc/pyEDAA.IPXACT/GeneratorChain.rst
  doc/pyEDAA.IPXACT/index.rst
  doc/pyIPXACT.rst
  doc/requirements.txt
  pyEDAA/IPXACT/Catalog.py
  pyEDAA/IPXACT/Component.py
  pyEDAA/IPXACT/Design.py
  pyEDAA/IPXACT/DesignConfiguration.py
  pyEDAA/IPXACT/GeneratorChain.py
  pyEDAA/IPXACT/__init__.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: bug, enhancement

#9 Updated reference to IPXACT-Schema
  .gitmodules
Labels: enhancement, dependencies

#10 Cleanup
  .github/workflows/Pipeline.yml
  .gitignore
  .vscode/settings.json
  README.md
  doc/Makefile
  doc/shields.inc
  setup.py
Labels: enhancement
